version: "3.8"

services:
  nginx:
      build: ./requirements/nginx
      container_name: nginx
      ports:
       - 443:443
       - 80:80
  mariadb:
      build: ./requirements/mariadb
      container_name: mariadb
      environment:
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
        - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
        - WORDPRESS_STANDARD_USER_PASSWORD=${WORDPRESS_STANDARD_USER_PASSWORD}
        - WORDPRESS_STANDARD_USER=${WORDPRESS_STANDARD_USER}
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
      volumes:
        - ${VOLUMES_ROOT_PATH}/mariadb:/var/lib/mysql
      ports:
        - 3306:3306
  wordpress:
      build: ./requirements/wordpress
      container_name: wordpress
      ports:
        - 9000:9000

        