version: "3.8"

services:
  nginx:
      build: ./requirements/nginx
      ports:
       - 80:80
  mariadb:
      build: ./requirements/mariadb
      environment:
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
        - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}

