version: "3.8"

services:
  nginx:
      build: ./requirements/nginx
      container_name: nginx
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
      volumes:
        - ../www:/var/www
        - ./requirements/nginx/web:/var/web
      ports:
        - 443:443
      networks:
        - internal

  mariadb:
      build: ./requirements/mariadb
      container_name: mariadb
      environment:
        - WP_DB_NAME=${WP_DB_NAME}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
      volumes:
        - ${VOLUMES_ROOT_PATH}/mariadb:/var/lib/mysql
      ports:
        - 3306:3306
      networks:
        - internal

  wordpress:
      build: ./requirements/wordpress
      container_name: wordpress
      environment:
        - WP_DB_NAME=${WP_DB_NAME}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
        - WP_USER_PASSWORD=${WP_USER_PASSWORD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_TITLE=${WP_TITLE}
        - WP_USER_EMAIL=${WP_USER_EMAIL}
        - WP_USER=${WP_USER}
        - WP_URL=${WP_URL}
        - WP_MARIADB_HOSTNAME=${WP_MARIADB_HOSTNAME}
        - WP_REDIS_PORT=${WP_REDIS_PORT}
        - WP_REDIS_HOST=${WP_REDIS_HOST}
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
      volumes:
        - ../www:/var/www
      ports:
        - 9000:9000
      networks:
        - internal

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - internal
  
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - 21:21
    volumes:
        - ../www:/var/www
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    networks:
      - internal
  
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - internal

  redis-ui:
    build: ./requirements/bonus/redis-ui
    container_name: redis-ui
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - 8081:8081
    networks:
      - internal

  portfolio:
    build: ./requirements/bonus/portfolio
    volumes:
      - ../../dunny:/var/www/dunny
    networks:
      - internal

networks:
  internal:
    driver: bridge
